/*
Piste Gomez Cristian Jovani
3CV5
Proyecto para ETS Ordinario de compiladores
Interprete Mini-Logo
17/06/2019
Compiladores
*/
//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################
/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class ParserVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public ParserVal()
{
}
/**
 * Initialize me as an int
     * @param val
 */
public ParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
     * @param val
 */
public ParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
     * @param val
 */
public ParserVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
     * @param val
 */
public ParserVal(Object val)
{
  obj=val;
}
}//end class

